project_id = "fnxivlswzswbrnfxldal"

[functions.create-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.sharepoint-manager]
verify_jwt = false

[functions.generate-solicitacao-pdf]
verify_jwt = false