// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxivlswzswbrnfxldal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueGl2bHN3enN3YnJuZnhsZGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDM4MzcsImV4cCI6MjA4NzQxOTgzN30.NAFGtebJXcRBeJir0mIQWmcKgERsDuj5cWMpPnccVrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});